version: '3'

services:
  db:
    image: recipethesaurus.azurecr.io/postgres:12.9
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dbnet
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data

  search:
    image: recipethesaurus.azurecr.io/elasticsearch:8.6.1
    container_name: search
    environment:
      ELASTICSEARCH_CLUSTER_NAME: fusionauth
      ELASTICSEARCH_IS_DEDICATED_NODE: yes 
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - searchnet
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - searchdata:/usr/share/elasticsearch/data

  fusionauth:
    image: recipethesaurus.azurecr.io/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch

    networks:
      - dbnet
      - searchnet
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauthconfig:/usr/local/fusionauth/config

networks:
  dbnet:
    driver: azure-vnet 
  searchnet:
    driver: azure

volumes:
  dbdata:
    driver: azure_file
    driver_opts:
     share_name: dbdata
     storage_account_name: recipethesaurusstorage
  fusionauthconfig:
   driver: azure_file
   driver_opts:
    share_name: fusionauthconfig
    storage_account_name: recipethesaurusstorage
  searchdata:
   driver: azure_file
   driver_opts:
    share_name: searchdata
    storage_account_name: recipethesaurusstorage
